Module2 task1
htmlacademy-vue/394677-pizza-1 pull request #2
Opened 2021-07-21 17:02 UTC by mikheyeva

2021-07-21 18:03 UTC, Djaler requested changes

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/static/pizza.json
> +      "class": "light",
нельзя модифицировать json, потому что в дальнейшем эти данные будут приходить с бекенда

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/static/pizza.json
> +      "class": "light",
Нужно расширить данные из json с помощью хелперов (пример в учебном проекте https://github.com/htmlacademy-vue/VueWork/blob/3718ac240e02ed588be8cedc459be53b05515d8f/src/frontend/src/common/helpers.js#L29)

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/common/components/AppDrop.vue
> +  <div @drop.stop="onDrop" @dragover.prevent @dragenter.prevent>
нигде не используется AppDrop

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
draggable должен отключаться, если достигнуто максимальное количество одинаковых ингредиентов (3)

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +        this.item.price = Math.abs(this.item.price);
тут мутируется объект, переданный через пропс. Так во Vue делать нельзя, нужно явно передавать данные наверх с помощью событий

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      disabledAdd: false,
disabledReduce и disabledAdd хорошо бы сделать computed-свойствами

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +import { DATA_TRANSFER_PAYLOAD, MOVE } from "@/common/constants.json";
это, по идее, должны быть строки, а там пустые объекты

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/App.vue
> +    <AppLayout></AppLayout>
правильнее будет в AppLayout сделать слот и в нем рендерить Index

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +        this.$emit("changeIngredientClassList", this.ingredientClassList);
ingredientClassList явно должен вычисляться не в этом компоненте

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      totalPrice: 0,
цену нужно вычислять с помощью computed

2021-07-21 18:03 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    pizzaDoughClass: {
этот компонент должен принимать не классы, а конфигурацию пиццы (ингредиенты, тесто и т.д.), а все необходимые вещи для отображения формировать сам

2021-07-23 13:45 UTC, mikheyeva commented on src/frontend/src/App.vue
> +    <AppLayout></AppLayout>
в AppLayout  ведь нужно было вынести header? я это правильно сделала? Если вставить в AppLayout Index через слот, то ломается верстка

2021-07-23 15:08 UTC, Djaler commented on src/frontend/src/App.vue
> +    <AppLayout></AppLayout>
Да, хедер должен быть в лейауте, всё верно.
Просто обернуть ещё в один div, чтобы рядом был header и slot

2021-07-23 16:02 UTC, mikheyeva commented on src/frontend/src/views/Index.vue
> +      totalPrice: 0,
не вижу возможным сделать это через computed

2021-07-23 16:05 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      totalPrice: 0,
для того чтобы это сделать, нужно при выборе теста/размера/etc не сразу модифицировать цену, а фиксировать выбранную опцию в data, изменять count для нужного ингредиента и т.д.. Тогда в computed можно будет сложить цены за выбранные ингредиенты, умножить на размер пиццы и вот это вот всё (точная формула расчета есть в ТЗ)

2021-07-23 16:08 UTC, mikheyeva commented on src/frontend/src/common/components/ItemCounter.vue
> +        this.item.price = Math.abs(this.item.price);
я сделала копию объекта, изменяю и передаю ее

2021-07-23 16:08 UTC, mikheyeva commented on src/frontend/src/common/components/ItemCounter.vue
> +      disabledAdd: false,
сделала

2021-07-23 16:09 UTC, mikheyeva commented on src/frontend/src/common/components/AppDrag.vue
> +import { DATA_TRANSFER_PAYLOAD, MOVE } from "@/common/constants.json";
заменила

2021-07-23 16:09 UTC, mikheyeva commented on src/frontend/src/App.vue
> +    <AppLayout></AppLayout>
спасибо. сделала

2021-07-23 16:09 UTC, mikheyeva commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +        this.$emit("changeIngredientClassList", this.ingredientClassList);
вынесла

2021-07-24 12:17 UTC, mikheyeva commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
есть

2021-07-24 12:18 UTC, mikheyeva commented on src/frontend/src/views/Index.vue
> +      totalPrice: 0,
вынесла в computed

2021-07-24 14:55 UTC, mikheyeva commented on src/frontend/src/static/pizza.json
> +      "class": "light",
убрала изменения из json, но добавляю недостающие данные через computed, а не хелпер

2021-07-24 14:57 UTC, mikheyeva commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    pizzaDoughClass: {
здесь не вышло. Компонент вычисляемые свойства компонента и методы не реагируют на изменения внутри массивов, которые я передаю и не пересчитывают классы. Не реагирует и через wath (хотя например изменение name видит)

2021-07-24 15:02 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +    pizzaDoughClass: {
Значит ломается реактивность. Вероятно нужно использовать Vue.set

2021-07-24 15:55 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +    :draggable="true"
prop draggable в компонент добавлен, но не используется

2021-07-24 15:56 UTC, Djaler commented on src/frontend/src/common/components/AppDrag.vue
> +import { DATA_TRANSFER_PAYLOAD, MOVE } from "@/common/constants.json";
ну не пустые строки, опять таки
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer

2021-07-24 16:01 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +        this.localItem.price = Math.abs(this.localItem.price);
мутируется computed-свойство. это тоже неправильно. К тому же, зачем переназначать ему цену, она же никак не меняется

2021-07-24 16:02 UTC, Djaler commented on src/frontend/src/common/components/ItemCounter.vue
> +      this.localItem.count = this.value;
не нужно модифицировать item локально чтобы бросить его в событии. Можно использовать spread оператор, например

2021-07-24 16:04 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    draggable() {
это неправильно работает. draggable отключается для всех ингредиентов, если какого-то из них добавили 3 штуки.
Должен отключаться draggable только для конкретного ингредиента при достижении максимального количества

2021-07-24 16:07 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      this.ingredients[index].count = item.count;
опять таки, мутируется computed-свойство

2021-07-24 16:12 UTC, Djaler commented on src/frontend/src/views/Index.vue
> +      doughPrice: 0,
правильный способ организации данных в этой задаче - из компонентов билдера выбрасывать событиям и держать здесь, в data Index, целиком объекты выбранного теста, размера, соуса, а также список выбранных ингредиентов с их количеством. 
И дальше эти данные передаются в BuilderPizzaView, где вычисляются нужные классы для отображения и т.д., по этим данным считается цена. Тот подсчет цены, что есть сейчас - неправильный, потому что размер пиццы не просто прибавляет 100/200/300 единиц (это, кстати, нужно убрать из json), а умножает цену за выбранные ингредиенты и т.д. в 1/2/3 раза

2021-07-24 17:25 UTC, mikheyeva commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    ingredients: {
этот вотчер не срабатывает. можешь ли сказать почему?

2021-07-24 19:34 UTC, Djaler commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +    ingredients: {
Потому что в проп ingredients в Index.vue передаётся результат computed-свойства ingredients, значение которого мутируется в методе countIngredient. Нельзя мутировать значение computed-свойства. Нужно менять значения, на основании которых свойство пересчитается. То, что ломается реактивность - следствие этого

2021-07-26 18:11 UTC, merged